# Generated by Django 6.1 on 2026-08-23 13:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Recipe",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("rname", models.CharField(max_length=100)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("breakfast", "Breakfast"),
                            ("first_dish", "Appetizers"),
                            ("soup", "Soups"),
                            ("salad", "Salads"),
                            ("main_dish", "Main Dishes"),
                            ("side_dish", "Side Dishes"),
                            ("dessert", "Desserts"),
                            ("drink", "Drinks"),
                            ("bake", "Baking"),
                        ],
                        default="main_dish",
                        max_length=20,
                    ),
                ),
                ("secret", models.BooleanField(default=False)),
                ("portions", models.IntegerField(default=1)),
                (
                    "ingredients",
                    models.TextField(
                        help_text="Enter each amount & ingredient on a new line"
                    ),
                ),
                (
                    "guidance",
                    models.TextField(help_text="Enter preparation steps on new lines"),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recipes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
